### PR TITLE
Add glue 4.0 as a valid glue version

### PR DESCRIPTION
**Pull request by Staberinde**
According to https://docs.aws.amazon.com/glue/latest/dg/migrating-version-40.html#migrating-version-40-from-30 the API Interface remains unchanged between 3.0 and 4.0

### CODE REVIEW

**Review by jhpyke — APPROVED** [review]
looks good to me

**Review by jhpyke — CHANGES_REQUESTED** [review]
Can you fix the one build failure? Looks like a missing package

**Review by jhpyke — APPROVED** [review]
Nice fix - looks good to go!

**Comment by Staberinde** [comment]
@jhpyke should I increment the version in `pyproject.toml`/add changelog as part of this PR or separately? If part of this PR, would you agree that this is a [minor version increment](https://semver.org/)?

**Comment by jhpyke** [comment]
My instinct for cleanliness would be to have a single explicit 'release' PR where you update the `pyproject`, incorporating the updates to the Release Notes as well, but I think it's perfectly reasonable if you want to do it as part of this PR. I would agree with you that this represents a 'minor' level change - textbook `add[ing] functionality in a backward compatible manner` work based on the AWS release notes.

**Pull request merged**
